### ISSUE TITLE
--alpha Arguments written in hprd.config and irefindex.config

### ISSUE THREAD

**Issue by hd00ljy** [raphael-group/hotnet2#11]
Through last update(June 12), it seems the --alpha argument required by makeRequiredPPRFiles.py was chaged into --beta argument,
but inside hprd.config and irefindex.config, --alpha hasn't been changed to beta.

hprd.config
--edgelist_file influence_matrices/hprd/hprd_edge_list
--gene_index_file influence_matrices/hprd/hprd_index_genes
--prefix hprd
--alpha 0.60
--output_dir influence_matrices/hprd

**Comment by asifrim** [comment]
I was wondering exactly the same thing. Is beta=1-alpha?

**Comment by hd00ljy** [comment]
It seems so.

If you click the history button of makeRequiredPPRFiles.py and click the 2nd item ( remove matlab version of creating influence matrices. fix transpose b… …), then you can see the modification done on the alpha argument.
(https://github.com/raphael-group/hotnet2/commit/b49bace50cb2d2d742fdbb0bb1425ce379374560)

The descriptions on beta are the same before and after modification (beta is the restart probability for insulated heat diffusion process),
and within the explanation on alpha argument before modification, it says alpha is equal to 1-beta.


<before>
-        |-a/--alpha               | REQUIRED           |Page Rank dampening factor, equal to 1-beta (where beta is  |
-        |                         |                    |the restart probability for insulated heat                  |
-        |                         |                    |diffusion|process).                                         |

<after>
+        |-b/--beta                | REQUIRED           |Beta is the restart probability for the insulated heat      |
+        |                         |                    |diffusion process.                                          |

**Comment by mdml** [comment]
Thank you for noticing this, sorry for the inconvenience. We've fixed it in commit 0ba3f6e1123fd3106e75368bbf1ac575ad7c486a.
