### ISSUE TITLE
updating release tags

### ISSUE THREAD

**Issue by 0xaf1f** [raphael-group/hotnet2#34]
The latest tagged release is from 2015. It'd be nice to keep these up-to-date to avoid working with intermediate development states and to know when to update our installations. I've just take a user request to install this on our cluster and having these things would help me out.

Thanks for your consideration!

**Comment by matthewreyna** [comment]
Thank you for the very good suggestion.  We added two new tagged releases, where v1.1.0 includes assorted updates since v1.0.1 and v1.2.0 includes breaking changes with a simpler interface and other features.
