### ISSUE TITLE
Incorrect Edges Lead to Disconnected Components

### ISSUE THREAD

**Issue by dnusinow** [raphael-group/hotnet2#40]
Hello,

   I'm trying to run HotNet2 on the BioPlex network (located at http://bioplex.hms.harvard.edu/data/BioPlex_interactionList_v4a.tsv) . After running the program I noticed a component with a pair of nodes that was disconnected from the others. Even at the minimal component size threshold being higher than two, the pair was present in the data.

   I've been trying to debug the program and I've traced the issue as best as I could to narrow it down. Here's what I've found:
 
1. The two nodes are not connected to any of the other nodes that are output as being in the same component in the original network. This appears to be true in the network as read in from the hdf5 file as well as the original text file.
2. The two nodes are connected to one other node in the network internally. This appears to happen after the weighted graph is constructed in the run_helper function.
3. When the visualization is output, the program looks at the original network (read through the hdf5 file) and not the weighted graph constructed by the similarity matrix, so that pair of nodes is disconnected.

I have a hard time understanding how the simliarity_matrix() and weighted_graph() functions are supposed to work, and my Python skills aren't great, so I've hit a wall in debugging this. Overall though, it looks like there's some errors with how the network is represented internally in the program. 

Please let me know if I can be of more help here. I know I haven't provided many specifics, but I haven't figured out how to narrow the test case down to a small example that's trivially reproduced.

**Comment by matthewreyna** [comment]
HotNet2 subnetworks are not necessarily connected in the original network, e.g., BioPlex, but the HotNet2 visualization shows the HotNet2 subnetworks with these original network interactions.

For example, suppose that nodes _u_ and _v_ are high scoring but do not interact directly.  If there are many paths between _u_ and _v_, then HotNet2 may identify a strong "influence" between these two genes, so HotNet2 may form a subnetwork containing _u_ and _v_ that could be disconnected.  In this case, HotNet2 is able to infer a relationship between _u_ and _v_ even though _u_ and _v_ do not interact directly in the observed network.

Please see the "Identification of hot subnetworks" section of the Online Methods of Leiserson _et al._, _Nat. Gen._, 2014 for more details about how HotNet2 identifies subnetworks.

**Comment by dnusinow** [comment]
Thank you for the reply! I didn't realize that this was the expected behavior, but it sounds like from your explanation that it is. I'll have to rethink how to report a subnetwork that has more than one component. If you've got any advice on how to manage that I'd appreciate it. Either way, thank you for your time, and I'll close this bug.
