### ISSUE TITLE
makeHeatFile.py  scores  -hf data/heats/pan12.gene2mutsig.txt or mutsig flag?

### ISSUE THREAD

**Issue by cgpu** [raphael-group/hotnet2#44]
Hi @matthewreyna, I was running a test today to make sure that as many functionalities of HotNet2 are exposed. Quick question, I observed here that the filename denotes `mutsig`, however `makeHeatFile.py scores` is used (see below for line).

https://github.com/raphael-group/hotnet2/blob/0f12ff0112ee00033f4163666cef665c05bb4c6e/paper/paper_commands.sh#L49-L51

Can you verify if is this correct?

Refering to the `usage` info of `makeHeatFile.py`,  each file  should be run with the appropriate arguments, and wanted to make sure everything is correct in this bit.

```
makeHeatFile.py \ 
mutsig --mutsig_score_file \
MUTSIG_SCORE_FILE
```

```
makeHeatFile.py \
mutation --snv_file \
SNV_FILE 
```

```
makeHeatFile.py \
scores --heat_file \
HEAT_FILE
```

```
usage: makeHeatFile.py \
music --music_score_file \
MUSIC_SCORE_FILE
```

**Comment by matthewreyna** [comment]
Yes, the lines of code in the `paper_commands.sh` script are correct.

The command

`    makeHeatFile.py mutsig --mutsig_score_file MUTSIG_SCORE_FILE`

loads raw MutSig q-values, but the code in the `paper_commands.sh` script loads MutSig q-values that have already been processed (log-transformed, etc.).

**Comment by cgpu** [comment]
I see, thanks @matthewreyna. Feel free to close this.
