### ISSUE TITLE
burden test

### ISSUE THREAD

**Issue by dwaggott** [raphael-group/hotnet2#6]
Nice paper.

Is it possible to fudge the analysis to perform on generic gene level p/q values? I've got lot's of germline burden testing results that I'd like to test.

Daryl

**Comment by mdml** [comment]
Daryl,

Yes, you can provide HotNet2 any non-negative gene-level scores. You could take the negative log of the p/q values so that lower p-values are given higher scores.

Max

**Comment by dwaggott** [comment]
Thanks :) I'll update on progress.

On Mon, Jan 19, 2015 at 7:27 PM, Jonathan Eldridge <notifications@github.com
