### ISSUE TITLE
HINT & MULTINET influence matrices

### ISSUE THREAD

**Issue by jamesrpriest** [raphael-group/hotnet2#8]
Thanks for providing the permutations for these additional protein interaction datasets mentioned in the Nature Genetics paper. However in each downloaded dataset I don't see the  "dataset"_edge_list representing the true (not permuted) protein interactions within the network and neither do I see them in the main package. Are these available for download somewhere else?

**Comment by asifrim** [comment]
I found them here:
http://compbio-research.cs.brown.edu/pancancer/hotnet2/#!/data
